### ISSUE TITLE
error in run backend

### ISSUE THREAD

**Issue by Mohammadwh** [NickHackman/telegram-clone-py#17]
hi how i can fix this error?

![image](https://user-images.githubusercontent.com/18552903/80859870-1fc29a00-8c79-11ea-9e7f-25b569fd9d18.png)

**Comment by NickHackman** [comment]
This is most likely a result of SQLAlchemy expecting there to be a sqlite3 database located at `/backend/telegram-clone-py.db`, this probably should be specified in the configuration file, but I didn't exactly get to that when working on this project.
